### ISSUE TITLE
EOS Citrine on CentOS 7 - deployment issues

### ISSUE THREAD

**Issue by dragosdmtrsc** [cern-eos/eos#12]
Hello, guys,
I am facing some issues while attempting to install an EOS Citrine deployment on CentOS 7. In short, I have an EOS MGM and 3 FSTs. When trying to copy a file to EOS (via configured fuse mount), I keep getting the following error:
cp: cannot create regular file ‘/eos/\<instance name\>/test/common.sh’: No space left on device
even though `df -ah /eos/` yields

Filesystem      Size  Used Avail Use% Mounted on
eosmain         3,0T  235M  3,0T   1% /eos

The file systems are in the online state.
I am using no replication layout, only working with a fresh default installation.
What could go wrong?

**Comment by franck-eyraud** [comment]
Hello,
When trying an upgrade to Citrine, I had to change the FST configuration to add a value (anything, but something) to EOS_GEOTAG, otherwise no write could be scheduled to any FST, and the error message was the same that you are having. This is done in` /etc/sysconfig/eos` on each fst (then restart eos service) 

```
export EOS_GEOTAG='default'
```

Hope this might solve your issue.

**Comment by dragosdmtrsc** [comment]
Thank you for your reply! Indeed, this solved the issue I was facing
